openapi: 3.0.3
info:
  title: RAG API
  description: API для проверки состояния сервера и обработки запросов от фронтенда.
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Локальный сервер

paths:
  /api/status:
    get:
      summary: Проверка состояния сервера
      description: Возвращает сообщение, подтверждающее, что сервер работает.
      operationId: status
      tags:
        - api
      responses:
        '200':
          description: Сервер работает
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Alive"

  /api/ask:
    post:
      summary: Отправка запроса от пользователя
      description: Принимает запрос от пользователя в формате JSON и возвращает полученные данные.
      operationId: ask
      tags:
        - api
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AskRequest'
      responses:
        '200':
          description: Успешный ответ на запрос
          content:
            application/json:
              schema:
                type: object
                properties:
                  received_query:
                    type: string
                    description: Полученный запрос от пользователя
                    example: "What is the capital of France?"
                  received_token:
                    type: string
                    nullable: true
                    description: Полученный токен (если передан)
                    example: "user123"
        '422':
          description: Ошибка валидации входных данных
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: array
                    items:
                      type: object
                      properties:
                        loc:
                          type: array
                          items:
                            type: string
                        msg:
                          type: string
                        type:
                          type: string

components:
  schemas:
    AskRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: Текст запроса пользователя
          example: "What is the capital of France?"
        token:
          type: string
          nullable: true
          description: Токен пользователя для аутентификации (опционально)
          example: "user123"